name: Build and Test

on:
  push:
    branches:
      - main  
  pull_request:
    branches:
      - main  # Change this to your main branch name if different

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t your-docker-image-name .

    - name: Test Docker container
      run: docker run --rm -p 4949:4949 your-docker-image-name python -m pytest tests/

    - name: Push Docker image to Docker Hub (optional)
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: your-docker-image-name:latest