name: Build and Test Docker

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:19.03.12
        options: --privileged
        ports:
          - 8080:8080

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t apptest:latest .

    - name: Run Docker container
      run: docker run -d -p 4949:4949 apptest:latest

    - name: Wait for the container to be ready
      run: |
        while ! curl -s http://localhost:4949 > /dev/null; do
          echo "Waiting for container..."
          sleep 3
        done

    - name: Run tests
      run: |
        # Example command to run tests
        curl localhost:4949

    - name: Log in to Amazon ECR
      id: ecr-login
      uses: aws-actions/amazon-ecr-login@v2
      with:
        region: ${{ secrets.AWS_REGION }}
        

    - name: Build Docker image
      run: |
        # Get the ECR repository URI
        REPOSITORY_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"
        
        # Build the Docker image
        docker build -t $REPOSITORY_URI:latest .
      
    - name: Push Docker image to ECR
      run: |
        # Get the ECR repository URI
        REPOSITORY_URI="${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ secrets.ECR_REPOSITORY }}"
        
        # Push the Docker image to ECR
        docker push $REPOSITORY_URI:latest
